### ISSUE TITLE
floating point exception[BUG]

### ISSUE THREAD

**Issue by quarterturn** [theroyallab/tabbyAPI#137] opened 2024-06-13 18:43 UTC
**Describe the bug**
Running tabbyAPI eventually exits with "floating point error"

**To Reproduce**
1. python main.py --host 0.0.0.0
2. autosplit loading llama-3-8B-iterative-DPO-final-exl2

**Expected behavior**

**Logs**
[11187.730688] traps: pt_main_thread[1995] trap divide error ip:7fd9cb0a7751 sp:7ffe38f3a860 error:0 in exllamav2_ext.cpython-311-x86_64-linux-gnu.so[7fd9cb02a000+ab000]

strace from the main thread:
```
getsockname(68, {sa_family=AF_INET, sin_port=htons(5000), sin_addr=inet_addr("192.168.0.50")}, [16]) = 0
getpeername(68, {sa_family=AF_INET, sin_port=htons(56800), sin_addr=inet_addr("192.168.0.50")}, [16]) = 0
epoll_ctl(46, EPOLL_CTL_ADD, 68, {events=EPOLLIN, data={u32=68, u64=140724603453508}}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=11677, tv_nsec=156386082}) = 0
epoll_wait(46, [{events=EPOLLIN, data={u32=68, u64=140724603453508}}], 3, 0) = 1
clock_gettime(CLOCK_MONOTONIC, {tv_sec=11677, tv_nsec=156544136}) = 0
recvfrom(68, "POST /v1/completions HTTP/1.1\r\nC"..., 262144, 0, NULL, NULL) = 12986
clock_gettime(CLOCK_MONOTONIC, {tv_sec=11677, tv_nsec=157049447}) = 0
epoll_wait(46, [], 3, 0)                = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=11677, tv_nsec=157187526}) = 0
getpid()                                = 2419
getpid()                                = 2419
getpid()                                = 2419
clock_gettime(CLOCK_MONOTONIC, {tv_sec=11677, tv_nsec=160655909}) = 0
epoll_wait(46, [], 3, 0)                = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=11677, tv_nsec=160795873}) = 0
getpid()                                = 2419
getpid()                                = 2419
getpid()                                = 2419
getpid()                                = 2419
getpid()                                = 2419
getpid()                                = 2419
clock_gettime(CLOCK_MONOTONIC, {tv_sec=11677, tv_nsec=161641807}) = 0
epoll_wait(46, [], 3, 0)                = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=11677, tv_nsec=161778908}) = 0
getrandom("\xea\x79\x4e\x12\xd5\x2b\xf2\x13\xbc\x35\xfc\x32\xe0\x0f\xde\x91", 16, 0) = 16
getrandom("\x10\x1b\x3a\x72\x9a\x56\x68\x25\x89\x98\xda\xa9\xe5\xd4\x17\x3e\x2b\x46\x62\xfd\xc3\x13\x11\x2e\x40\xa1\xe2\x1a\x27\x41\x29\x62"..., 2496, GRND_NONBLOCK) = 2496
mmap(NULL, 131338240, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fcb382bf000
clock_gettime(CLOCK_REALTIME, {tv_sec=1718303962, tv_nsec=100568382}) = 0
getpid()                                = 2419
getpid()                                = 2419
getpid()                                = 2419
getpid()                                = 2419
clock_gettime(CLOCK_MONOTONIC, {tv_sec=11677, tv_nsec=183937168}) = 0
epoll_wait(46, [], 3, 0)                = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=11677, tv_nsec=184108561}) = 0
getpid()                                = 2419
getpid()                                = 2419
clock_gettime(CLOCK_MONOTONIC, {tv_sec=11677, tv_nsec=184433050}) = 0
getpid()                                = 2419
clock_gettime(CLOCK_MONOTONIC, {tv_sec=11677, tv_nsec=184609822}) = 0
epoll_wait(46, [], 3, 0)                = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=11677, tv_nsec=184749926}) = 0
clock_gettime(CLOCK_REALTIME, {tv_sec=1718303962, tv_nsec=102125942}) = 0
--- SIGFPE {si_signo=SIGFPE, si_code=FPE_INTDIV, si_addr=0x7fcf1b0a7751} ---
+++ killed by SIGFPE +++
Floating point exception
```

**System info** (Bugs without this information will go lower on our priority list!)
 - OS: Debian 12
 - Python version: 3.11
 - CUDA/ROCm version: 12.4
 - tabbyAPI from current main

**Additional context**
nvidia-smi:
```
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3090        On  |   00000000:02:00.0 Off |                  N/A |
|  0%   46C    P8             27W /  350W |       1MiB /  24576MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  Tesla P100-PCIE-16GB           On  |   00000000:03:00.0 Off |                    0 |
| N/A   36C    P0             27W /  250W |       0MiB /  16384MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   2  Tesla P100-PCIE-16GB           On  |   00000000:04:00.0 Off |                    0 |
| N/A   35C    P0             28W /  250W |       0MiB /  16384MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   3  NVIDIA GeForce RTX 2080 Ti     On  |   00000000:A1:00.0 Off |                  N/A |
| 17%   35C    P8             19W /  250W |       0MiB /  22528MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   4  NVIDIA GeForce RTX 3090        On  |   00000000:A2:00.0 Off |                  N/A |
| 45%   49C    P8             29W /  370W |       1MiB /  24576MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
```

**Comment by turboderp** [comment] 2024-06-13 19:00
What sampler settings are you using?

**Comment by quarterturn** [comment] 2024-06-13 19:10
I'm not setting one in the config. I have tried the following GPU pinning combos though:
auto-split and flash_attention disabled: eventual floating point error
pinned to P100s and flash_attention disabled: eventual floating point error
pinned to 3090s and flash_attention enabled: no floating point error
pinned to the 2080ti and flash_attention disabled: eventual floating point error

**Comment by turboderp** [comment] 2024-06-13 19:29
It's really hard to figure out where the error is actually happening, though. It would be helpful if it could be narrowed down somehow, since I'd usually rely on the stack to at least point me in the right direction. The strace output doesn't resemble any part of the exllamav2_ext codebase (seems to deal with both file I/O and network sockets?). Is it possible you could insert some print statements all over `generate()` in `backends/exllamav2/generate` to try to figure out how far it gets before failing?

Would there be a way you could insert some print statements

**Comment by quarterturn** [comment] 2024-06-13 19:47
I don't think this is particularly helpful, but here's where it's failing in backends/exllamav2/model.py:
```
    807     async def generate(self, prompt: str, **kwargs):
    808         """Generate a response to a prompt"""
    809         generations = []
    810         print("Calling self.generate_gen with " + prompt )
    811         async for generation in self.generate_gen(prompt, **kwargs):
    812             generations.append(generation)
    813         print("self.generate_gen completed")
```

**Comment by DocShotgun** [comment] 2024-06-14 03:28
Seems like it might be isolated to the non-paged compatibility mode for whatever reason. There's a user who encountered this using ROCm as well.

**Comment by turboderp** [comment] 2024-06-14 12:16
@quarterturn That's somewhat helpful. It means the error is likely happening somewhere in [this function](https://github.com/turboderp/exllamav2/blob/5996922a0f0937aa503efa773780f1648915d73e/exllamav2/generator/dynamic.py#L842), and then likely in either `prefill` or `iterate_gen`, somewhere.

Of particular interest would be anywhere `model.forward_chunk` is called (lines 1044, 1107 and 2214), since all of the inference is under there. Another possible spot is `ExLlamaV2Sampler.sample` on line 1725 which leads into the C++ sampling function in `exllamav2_ext`.

Thing is I've been completely unable to reproduce the error, but there is another user having the issue, with ROCm, and also getting no stack trace to tell me where to even start looking for a division by zero (or whatever the floating-point error is.) Would you be able to narrow it down a little further by adding some more print statements to exllamav2?

**Comment by quarterturn** [comment] 2024-06-14 19:12
I'll be able to test in about an hour.

**Comment by quarterturn** [comment] 2024-06-14 19:44
I've added debug print statements and reinstalled tabbyAPI, but I'm guessing it doesn't use that, since I don't see any of my print statements. I don't see it getting used with examples/minimal_chat.py either. I'll try with exui though.

**Comment by turboderp** [comment] 2024-06-15 01:44
I think I may have worked it out. It is just an outright oversight in how the fallback generator reuses the cache from the previous sequence when it exceeds the chunk size. Sorry it took a while. I've pushed what should be a fix to the exllamav2 dev branch.

**Comment by quarterturn** [comment] 2024-06-15 16:22
```
  File "/home/derp/.conda/envs/exllamav2/lib/python3.11/site-packages/flash_attn/flash_attn_interface.py", line 51, in _flash_attn_forward
    out, q, k, v, out_padded, softmax_lse, S_dmask, rng_state = flash_attn_cuda.fwd(
                                                                ^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

I made sure to do a 'export TORCH_CUDA_ARCH_LIST="6.0 6.1 7.0 7.5 8.0 8.6 8.7 8.9"' and then a "pip install --force-reinstall --no-cache-dir" on exllamav2 and then tabbyAPI, so I'm pretty sure they have a torch built supporting CU6.0 for the P100s.

**Comment by turboderp** [comment] 2024-06-15 21:47
Do you have a little more of that stack trace? I'm not understanding why it's trying to use flash-attn. Are you getting [this warning](https://github.com/theroyallab/tabbyAPI/blob/85387d97adab7b9920095a4fc5fba4a4d37ad6eb/backends/exllamav2/model.py#L204) when launching the server?

**Comment by quarterturn** [comment] 2024-06-15 23:56
[strace.zip](https://github.com/user-attachments/files/15855668/strace.zip)
I caught it with '-f'. Tried adding '-k' but that was super-slow.

**Comment by quarterturn** [comment] 2024-06-19 20:49
Did you fix it? I'm no longer getting the error.

**Comment by turboderp** [comment] 2024-06-20 20:05
It's been fixed in exllamav2, yes. Or at least a bug was squashed that's probably this bug.

**Comment by bdashore3** [comment] 2024-06-29 00:08
Closing this issue because it's fixed in upstream.

**Closed by bdashore3** 2024-06-29 00:08 UTC
Labels: bug
