### ISSUE TITLE
[REQUEST] banned words

### ISSUE THREAD

**Issue by drago87** [theroyallab/tabbyAPI#145] opened 2024-07-04 16:25 UTC
**Is your feature request related to a problem? Please describe.**
Some models have a tendency to always respond with specific words or sentences (for me it's 'Mary Jane shoes')

**Describe the solution you'd like**
A list or something with banned words that TabbyAPI will ask the model to reroll

**Describe alternatives you've considered**
I have tried using [[banned "Mary Jane shoes"]], [System note: BLACKLIST AI PHRASES: "Mary Jane shoes"], [OOC: BLACKLIST AI PHRASES: "Mary Jane shoes"]

**Why should this feature be added?**
To be able to block words phrases you really don't want

**Examples**
Shoes: Black Mary Jane shoes
vs
Shoes: Black Sneakers

**Additional context**
SillyTavern have it built in for Text Generation WebUI [Replacement tags (macros)](https://docs.sillytavern.app/usage/core-concepts/characterdesign/#replacement-tags-macros) nr 39. I don't know how it exactly does it

**Comment by bdashore3** [comment] 2024-07-04 22:09
Hi there! This is already present in the API with the parameter `banned_strings`.

In SillyTavern, open up the sampler adjustment window and add your phrase in the `Banned Tokens` box. Make sure to enclose the phrase in `""`. For example, add `"Mary Jane shoes"` inside that box. Separate each phrase by a newline.

This is also a tabby specific feature. I'm not sure if it works on other backends. Hope this helps.

**Comment by drago87** [comment] 2024-07-04 22:11
Good to know

**Comment by DocShotgun** [comment] 2024-07-05 01:34
I'm curious, what model likes to respond with "Mary Jane shoes" enough that it needs to be a banned string?

**Comment by drago87** [comment] 2024-07-05 01:39
Kooten/LemonadeRP-4.5.3-8bpw-exl2
And i have now tried using the banned token function but it still seams to want to use the words tried both with and without "

![opera_d0iFeAqO56](https://github.com/theroyallab/tabbyAPI/assets/6805712/725b68b6-6127-4ffe-ab1f-4363fd665226)
![opera_oHCxWn5F7N](https://github.com/theroyallab/tabbyAPI/assets/6805712/25036b62-f3ee-457b-a677-48d870bdafee)

**Comment by DocShotgun** [comment] 2024-07-05 02:11
It needs to be with quotes or else it will break the string into individual tokens like the output from your first edit.

**Comment by bdashore3** [comment] 2024-07-05 20:35
The second edit is a correct payload. There can be many reasons why you're still seeing those phrases that fall to the character, sampling, etc. But this doesn't seem to be a problem on tabby's side.

Like I stated in the previous posts, enclose the phrases in `""` and separate by newline in SillyTavern.

Since this is not a bug or request, I'll be closing this issue. However, you can always ask for help in the [support Discord](https://discord.gg/sYQxnuD7Fj) or [SillyTavern's server](https://discord.gg/sillytavern).

**Closed by bdashore3** 2024-07-05 20:35 UTC
