### ISSUE TITLE
[BUG] Unloading models - does not fully unload memory from CUDA

### ISSUE THREAD

**Issue by sammcj** [theroyallab/tabbyAPI#144] opened 2024-06-29 00:44 UTC
**Describe the bug**

When unloading models, TabbyAPI does not fully unload them from the GPUs.

Memory is left used on the used on the GPUs and unavailable to other processes until TabbyAPI is restarted.

<img width="1040" alt="image" src="https://github.com/theroyallab/tabbyAPI/assets/862951/b62f6e5c-c012-489f-953f-12766d042e56">

**To Reproduce**

Steps to reproduce the behaviour:
1. Load a model
2. Unload the model
3. Check GPU VRAM usage

**Expected behaviour**

When a model is unloaded, all GPU memory should unoccupied.

**Logs**

```
INFO:     Attempting to load a prompt template if present.
INFO:     Using template "llama-3-chat" for chat completions.
INFO:     Loading model: /app/models/bartowski_Replete-Coder-Llama3-8B-exl2
INFO:     Loading with autosplit
Loading model modules ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 67/67 0:00:00
INFO:     Model successfully loaded.

INFO:     172.22.0.26:37980 - "GET /v1/model HTTP/1.1" 200
INFO:     172.22.0.26:37980 - "GET /v1/lora HTTP/1.1" 200
INFO:     Model unloaded.
INFO:     172.22.0.26:37980 - "POST /v1/model/unload HTTP/1.1" 200
ERROR:    Sent to request: No models are currently loaded.
INFO:     172.22.0.26:37980 - "GET /v1/model HTTP/1.1" 400
ERROR:    Sent to request: No models are currently loaded.
INFO:     172.22.0.26:37980 - "GET /v1/lora HTTP/1.1" 400
```

**System info** (Bugs without this information will go lower on our priority list!)
 - OS: Fedora 40, Docker container
 - Python version: Whatever is in the container image, I think that's 3.11
 - CUDA/ROCm version: 12.5.0

**Comment by turboderp** [comment] 2024-06-29 10:54
This is expected behavior. PyTorch isn't designed to be able to destroy its own CUDA context, so once you've used a device at all, you'll have VRAM buffers and kernels allocated on it, and the only way to free those resources is to kill the process. Not sure if it makes sense to consider an API that allows that. (?)

**Comment by sammcj** [comment] 2024-06-29 23:11
Oh really! That is interesting. I haven't seen this with other torch software, I thought that if you did a torch.cuda.empty_cache there should be no running CUDA processes consuming memory on your GPU(s).

What I have seen before is if empty_cache is called before objects containing references to tensors are deleted - the cache is not properly emptied.

Looking at model.py, I wonder if something like this would do it?

```python
del self.model
del self.draft_model
del self.config
del self.cache
del self.tokenizer
del self.generator

torch.cuda.synchronize()
torch.cuda.empty_cache()
```

**Comment by sammcj** [comment] 2024-06-29 23:19
e.g. something like https://github.com/theroyallab/tabbyAPI/compare/main...sammcj:tabbyAPI:freecuda?expand=1

**Comment by turboderp** [comment] 2024-06-30 01:10
`del` just deletes a reference, it doesn't accomplish anything that setting the reference to `None` wouldn't do. The only difference is:

```python
x = 123
x = None
print(x)  # prints "None"

x = 123
del x
print(x)  # raises NameError
```

In either case it's the garbage collector that handles freeing up unreferenced resource. You can manually clear the tensor cache, which Tabby already does, but that has the same effect regardless of how the tensors were dereferenced beforehand.

```python
import torch, gc
x = torch.randn((20000, 20000), device = "cuda:1")  # allocate a bunch of VRAM
torch.cuda.synchronize()  # does nothing since there are no pending kernels
torch.cuda.empty_cache()  # does nothing since x is still referenced
x = None  # or del x, pick  your poison
gc.collect()  # for good measure
torch.cuda.empty_cache()  # frees up VRAM used by tensor cache
```

You'll still be left with the Torch+CUDA overhead afterwards. You can measure the overhead by launching a Python console, and simply:

```python
import torch
x = torch.randn((1), device = "cuda:1")
```

Then check `nvidia-smi` and note that the process is already using something like 400 MB of VRAM on device 1. You can't get this back without killing the process, because it's not memory used by tensors. It's used by kernels, static buffers, data structures for the CUDA runtime and stuff like that. You'd have to fully destroy the CUDA context on that device to free it, and Torch just has no provisions for that.

Note that Torch will (typically?) use lazy initialization and allocate more context memory the first time you use any given kernel:

```python
import torch  # 0 MB (used by process)
x = torch.randn((10, 10), device = "cuda:1")  # 394 MB
y = torch.randn((10, 10), device = "cuda:1")  # 394 MB
z = x + y  # 454 MB
z = x @ y  # 484 MB
z = x.inverse()  # 514 MB
del x, y, z  #  514 MB
torch.cuda.synchronize()  # 514 MB
gc.collect  # 514 MB
torch.cuda.empty_cache()  # 512 MB
```

**Comment by sammcj** [comment] 2024-06-30 02:30
Ah I see, I might have to have a look at how https://github.com/oobabooga/text-generation-webui does it, as when you unload a model (exllamav2) there it is able to free all memory.

**Comment by turboderp** [comment] 2024-07-01 18:24
Well, I know one way it can be done is to load the entire inference engine (including Torch) in an isolated process which can then be killed to fully unload the model and free up all resources. I'm not sure if this is what TGW does, but it would make sense since it supports multiple backends, not all of which use Torch or CUDA in the first place.

**Comment by bdashore3** [comment] 2024-07-05 20:36
@sammcj This was a bug in exllamav2 upstream. Please see the associated PR

**Comment by sammcj** [comment] 2024-07-05 22:50
Ah I see, well thanks anyhow folks, I'll resort to restarting the docker container after each model unload.

**Comment by bdashore3** [comment] 2024-07-06 21:44
You can also build exllamav2 from source for the time being if you want to replicate TGW's behavior.

Closing this issue due to resolution.

**Closed by bdashore3** 2024-07-06 21:44 UTC
Labels: bug
