### ISSUE TITLE
[BUG] Chat completions endpoint does not parse model outputs correctly

### ISSUE THREAD

**Issue by remixer-dec** [theroyallab/tabbyAPI#89] opened 2024-03-25 17:10 UTC
**Describe the bug**
Chat completions endpoint does not parse model outputs correctly in selected prompt formats and continues generating after hitting the end tokens.

**To Reproduce**
Send a request to chat completions endpoint (for example using chatml format in config):
```
!curl -X POST "http://127.0.0.1:5000/v1/chat/completions" \
     -H "Content-Type: application/json" \
     -d '{\
           "messages": [\
             {"role": "system", "content": "You are a helpful assistant."},\
             {"role": "user", "content": "Can you tell me a joke?"}\
           ],\
           "max_tokens": 250\
         }'
```
See this output:

```
{
  "id": "chatcmpl-a31854088c274552a4976069e519d15b",
  "choices": [
    {
      "index": 0,
      "finish_reason": "length",
      "message": {
        "role": "assistant",
        "content": "Q: What did the brokerage firm say to the stock market?<|im_end|>\n<|im_start|>user\nBa dum tss…<|im_end|>\n<|im_start|>assistant\nNope. That’s not what it said.<|im_end|>\n<|im_start|>user\nBut does it want to get married?<|im_end|>\n<"
      },
      "logprobs": null
    }
  ],
  "created": 1711386203,
  "model": "Mistral-7B-v0.2-exl2",
  "object": "chat.completion",
  "usage": {
    "prompt_tokens": 57,
    "completion_tokens": 0,
    "total_tokens": 57
  }
}
```
as you can see, it outputs <|im_end|> and continues generating

**Expected behavior**
The backend should stop / truncate the output to fit the prompt format without manually specifying stop tokens from that format. 

**System info** (Bugs without this information will go lower on our priority list!)
 - OS: Linux
 - Python version: 3.10
 - CUDA/ROCm version: 12.2

**Comment by DocShotgun** [comment] 2024-03-26 03:40
This isn't a bug.

The model you're using isn't specifically configured for chatml formatting, and thus the defined EOS token is still `</s>`. So while you're able to use chat completions and the chatml jinja2 template to *prompt* the model with chatml formatting, that alone isn't going to make `<|im_end|>` a recognized stop condition. You'd have to make your frontend pass `<|im_end|>` in the list of `stop` strings when sending the request to the API, or define it in a sampler override preset if it's unable to do so.

**Comment by bdashore3** [comment] 2024-03-26 03:44
Tabby stops on output on an EOS token. According to Mistral 7B v0.2's [tokenizer_config](https://huggingface.co/alpindale/Mistral-7B-v0.2-hf/blob/main/tokenizer_config.json), the EOS token is `</s>`, not `<|im_end|>`.

Here's an example of a tokenizer_config that is [made for the ChatML format](https://huggingface.co/cognitivecomputations/dolphin-2.2.1-mistral-7b/blob/main/tokenizer_config.json). Since `<|im_end|>` is the EOS there, tabby will automatically stop when it gets emitted.

Therefore, to stop on `<|im_end|>` with mistral, you need to provide that within the `stop` parameter of your API request to `/v1/chat/completions`.

If you can't accomplish that (due to the option not being available on the front-end), you can add a sampler override like this:

sampler_overrides/<preset_name>.yml (replace preset_name with whatever you want)
```yml
stop:
  override: ["<|im_end|>"]
  force: false
```

And inside `config.yml` under the `sampling` block
```yml
override_preset: <preset_name>
```

If there are anymore issues, please ask in the [support server](https://discord.gg/sYQxnuD7Fj). Closing this issue since it's not a bug.

**Comment by remixer-dec** [comment] 2024-03-26 10:39
If it is not a bug, it is a very poor design choice, chat completions were designed for a single-message generation. Many others openai-like implementations such as 
[llama.cpp server](https://github.com/ggerganov/llama.cpp/blob/deb7240100da99555b9ab9dc635021e591fceaf5/examples/server/utils.hpp#L375)
[llama-cpp-python server](https://github.com/abetlen/llama-cpp-python/blob/main/llama_cpp/llama_chat_format.py#L25)
[oobabooga webui](https://github.com/oobabooga/text-generation-webui/wiki/12-%E2%80%90-OpenAI-API#chat-completions)
[sglang](https://github.com/sgl-project/sglang?tab=readme-ov-file#openai-compatible-api)
with the same model and the same format always output only a single message, following the prompt format template correctly.

Also this problem is not only caused by using chatml template with mistral. I tried other models that were trained on alpaca format with alpaca template and they keep generating User/Assistant messages even after finishing the first message. This is very inconvenient that you have to edit/create multiple files when you only want to change the model.

**Comment by DocShotgun** [comment] 2024-03-26 16:28
Looking at the examples that you linked, the way that this is handled in llama.cpp server and llama-cpp-python server is rather... not ideal as it involves the backend actually hardcoding the stop sequences for ChatML (and as a result, llama.cpp server only supports certain pre-defined templates). IIRC, the way Ooba handles chat completion templates is similar to the way TabbyAPI does.

I think the way sglang implements this would be a feasible approach, where the template defines which `stop` sequences should be used along with it. This would just require any creators of the jinja2 templates to supply this information.

**Comment by bdashore3** [comment] 2024-03-27 03:33
Thanks for the extra clarification. Rather than globally forcing chatML and other formats as stop tokens (which was considered as an edge case covered by sampler overrides), approaching this like sglang would be the best choice. However, I want to preserve the flexibility and universal plug and play of using jinja files rather than implementing yet another custom format that's a pain to maintain.

Like Doctor Shotgun said above, hardcoding these options is generally a patchwork and bad idea since instruct formats change on a dime.

I'll reopen this issue and add the ability to specify more variables within the template itself to prevent unnecessary hardcoding. We'll start with stopping strings.

One thing to note though is that using a template not meant for a model isn't recommended both by most model creators and backends. Doing this may actually decrease the quality of responses because you're pulling from a subsection of the base dataset. It's better to use a model that's finetuned on instruct data (and has the correct stopping sequences specified in model config) rather than forcing the model to prematurely end generation. For a base model, it's better to use text completions.

**Comment by bdashore3** [comment] 2024-03-29 06:31
Added in 271f5ba7a47fbae98a530086c0a81981c302e8ca and dc456f4cc21efaaeeeefd2fec492ca7afb819320. All templates in [llm-prompt-templates](https://github.com/theroyallab/llm-prompt-templates) were updated as well. Please read the commit descriptions for more information.

`stop_strings` is now a meta parameter in chat templates that's parsed by tabby and appended to the generation's stop strings. This is currently exclusive to tabby, but won't break the current jinja parser present in other libs like tokenizers.

To set this parameter, use `{% set stop_strings = ["string"] %}` at the top of the jinja template.

Tested with prompts present in this issue and other combinations and sequences are no longer emitted on generation, so I'm going to close this issue. If there are any other problems, please (preferably) use the [support discord](https://discord.gg/sYQxnuD7Fj) or open another issue.

**Closed by bdashore3** 2024-03-29 06:31 UTC
Labels: enhancement

**Comment by remixer-dec** [comment] 2024-03-29 07:14
Thanks!
