### ISSUE TITLE
[REQUEST] Remove default value of draft_model_dir let it can be defined tabby_config.yml

### ISSUE THREAD

**Issue by Originalimoc** [theroyallab/tabbyAPI#242] opened 2024-11-15 16:55 UTC
### Problem

tabby_config.yml can't override draft_model_dir in config.yml

### Solution

Currently the only workaround is set it to '/' so tabby_config.yml can set draft_model_name to a full path without leading '/'. Remove the default value "models" can make this cleaner.

### Acknowledgements

- [X] I have looked for similar requests before submitting this one.
- [X] I understand that the developers have lives and my issue will be answered when possible.
- [X] I understand the developers of this program are human, and I will make my requests politely.

**Comment by DocShotgun** [comment] 2024-11-15 17:44
Why would you want/need to override model directories with tabby_config.yml?

IMO, that’s something that should be a server config setting and not a model-specific config setting (which is what tabby_config.yml is intended for).

**Comment by Originalimoc** [comment] 2024-11-15 19:19
Hmmm plenty reason. Eg. You loaded a model from a separate disk/source and want to combine with another draft model placed elsewhere, some people even use NAS. What can you do except the workaround I commented above? Why arbitrarily limit yourself?

**Comment by DocShotgun** [comment] 2024-11-15 19:59
Why would you need the directory in which TabbyAPI searches for draft models to be dependent on what main model is currently loaded? That would be the use case for having draft model dir specified in tabby_config.yml instead of the main config.

It sounds like what you really want is for TabbyAPI to allow loading of models located in multiple different locations instead of a single directory each for models, draft models, and loras?

**Comment by bdashore3** [comment] 2024-11-15 23:12
I agree with @DocShotgun here and this feels out of scope. The inline loading schema is solely for specifying model parameters, not configuring directories. It assumes that you already have those directories configured. This allows for proper encapsulation of where files are located. If you wish to change where to look for models, change the `model_dir` and `draft_model_dir` keys in `config.yml`.

Another reason is because directories that are not listed in config.yml are also not iterated through on model list endpoints. This is by design since these endpoints are called very often by clients and complex logic would slow the server down in addition to breaking client/server parity.

Closing this issue.

**Closed by bdashore3** 2024-11-15 23:12 UTC

**Comment by Originalimoc** [comment] 2024-11-16 03:28
Not what I mean.
Later, it gotta be a cleaner way.

**Comment by Originalimoc** [comment] 2024-11-16 03:36
> Why would you need the directory in which TabbyAPI searches for draft models to be dependent on what main model is currently loaded? That would be the use case for having draft model dir specified in tabby_config.yml instead of the main config.
> 
> It sounds like what you really want is for TabbyAPI to allow loading of models located in multiple different locations instead of a single directory each for models, draft models, and loras?

That is, what I meant? The first part. Currently there is a default value "models" so you can't leave it blank in config.yml and configured it in tabby_config.yml

**Comment by DocShotgun** [comment] 2024-11-16 04:49
> That is, what I meant? The first part. Currently there is a default value "models" so you can't leave it blank in config.yml and configured it in tabby_config.yml

Then I would have to disagree that the param `draft_model_dir` should be configurable on a per-model basis, which is what you are suggesting if you want it to be set via `tabby_config.yml` rather than `config.yml`.
